app:
    container_name: symfony-docker-app
    image: ubuntu:trusty
    volumes:
        - .:/app
        - ./var/cache:/app/var/cache
        - /tmp
    tty: true

php:
    container_name: symfony-docker-php
    build: docker/php
    volumes_from:
        - app
    links:
        - mariadb
        - memcached
nginx:
  container_name: symfony-docker-nginx
  build: docker/nginx
  volumes_from:
      - app
  links:
      - php
  environment:
    VIRTUAL_HOST: symfony-docker.local
  ports:
    - "80:80"

mariadb:
  image: tutum/mariadb
  container_name: symfony-docker-mariadb
  environment:
    MARIADB_USER: admin
    MARIADB_PASS: admin
  ports:
    - 3306

memcached:
  image: memcached:1.4
  container_name: symfony-docker-memcached
  ports:
    - "11211:11211"
