web:
  build: .
  container_name: symfony-docker
  ports:
   - "8888:8888"
  volumes:
    - .:/app
    - ./docker/nginx/vhost_dev.conf:/etc/nginx/sites-enabled/default
  links:
    - mariadb
    - memcached
  environment:
    VIRTUAL_HOST: symfony-docker.dev
    VIRTUAL_PORT: 8888

mariadb:
  image: tutum/mariadb
  container_name: api-mariadb
  environment:
    MARIADB_USER: admin
    MARIADB_PASS: admin
  ports:
    - 3306

memcached:
  image: memcached:1.4
  container_name: api-memcached
  ports:
    - "11211:11211"
