version: '2'

services:

  app:
    container_name: sf.app
    build: .docker/php
    volumes:
      - .:/app

  nginx:
    container_name: sf.nginx
    build: .docker/nginx
    volumes_from:
      - app
    ports:
      - "8888:80"
